name: earthquakes

channels:
  - pyviz/label/dev
  - conda-forge

dependencies:
  - python
  - pip
  - jupyterlab
  - pandas
  # - conda-forge::geopandas

  - pyviz/label/dev::holoviews
  - pyviz/label/dev::geoviews
  - pyviz/label/dev::geoviews-core
  - pyviz/label/dev::param
  - pyviz/label/dev::panel

  - pyviz/label/dev::datashader
  # - pip:
  #   - -r requirements.txt
    

# conda install -c pyviz geoviews                    
#jupyter labextension install @pyviz/jupyterlab_pyviz     
#pip install --upgrade --force-reinstall shapely      
conda install -c conda-forge intake
conda install -c conda-forge intake-parquet

conda install -c pyviz hvplot